name: Latest blog post workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 * * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: varunsridharan/action-hashnode-blog@main
       with:
         USERNAME: "CodingThunder"
         STYLE: "blog"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         COUNT: 5
